In [4]:
import pandas as pd

In [7]:
df = pd.read_csv('data/events.csv', dtype={'sku':object})

In [8]:
df.head()

,timestamp,event,person,url,sku,model,condition,storage,color,skus,...,search_engine,channel,new_vs_returning,city,region,country,device_type,screen_resolution,operating_system_version,browser_version
0,2018-05-31 23:38:05,ad campaign hit,0004b0a2,/comprar/iphone/iphone-5s,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-05-31 23:38:05,visited site,0004b0a2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Paid,New,Camaragibe,Pernambuco,Brazil,Smartphone,360x640,Android 6,Chrome Mobile 39
2,2018-05-31 23:38:09,viewed product,0004b0a2,NaN,2694.0,iPhone 5s,Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-05-31 23:38:40,checkout,0004b0a2,NaN,2694.0,iPhone 5s,Bom,32GB,Cinza espacial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-05-29 13:29:25,viewed product,0006a21a,NaN,15338.0,Samsung Galaxy S8,Bom,64GB,Dourado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# some date processing
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day
df['weekday'] = df['timestamp'].dt.day_name()
df['hour'] = df['timestamp'].dt.hour
df['year_month_day'] = df['timestamp'].map(lambda x: str(x.year)+"/"+str(x.month)+"/"+str(x.day))
df['year_month_day'] = pd.to_datetime(df['year_month_day'])

In [30]:
def to_lower(obj):
    if type(obj) is str:
        return obj.lower()
    else:
        return obj
    

df.model.apply(lambda x: to_lower(x))

0                             NaN
1                             NaN
2                       iphone 5s
3                       iphone 5s
4               samsung galaxy s8
5                             NaN
6                             NaN
7               samsung galaxy s8
8                             NaN
9                             NaN
10                            NaN
11                            NaN
12                            NaN
13           motorola moto z play
14                            NaN
15                            NaN
16                            NaN
17                            NaN
18                            NaN
19                            NaN
20                            NaN
21                            NaN
22                  iphone 7 plus
23                            NaN
24                            NaN
25                            NaN
26                      iphone 6s
27                      iphone 6s
28                      iphone 6s
29                      iphone 6s
                    ...
1011258                       NaN
1011259                       NaN
1011260                       NaN
1011261                       NaN
1011262    samsung galaxy s7 edge
1011263    samsung galaxy s7 edge
1011264    samsung galaxy s7 edge
1011265    samsung galaxy s7 edge
1011266    samsung galaxy s7 edge
1011267    samsung galaxy s7 edge
1011268    samsung galaxy s7 edge
1011269    samsung galaxy s7 edge
1011270    samsung galaxy s7 edge
1011271    samsung galaxy s7 edge
1011272    samsung galaxy s7 edge
1011273                       NaN
1011274                       NaN
1011275    samsung galaxy s8 plus
1011276                       NaN
1011277                       NaN
1011278                       NaN
1011279                       NaN
1011280                       NaN
1011281    samsung galaxy s7 edge
1011282    samsung galaxy s7 edge
1011283    samsung galaxy s7 edge
1011284                       NaN
1011285                       NaN
1011286    samsung galaxy s7 edge
1011287    samsung galaxy s7 edge
Name: model, Length: 1011288, dtype: object

Â¿Por que XGBoost y no GradientBoost de sklearn, si son lo mismo supuestamente? 

https://stats.stackexchange.com/questions/282459/xgboost-vs-python-sklearn-gradient-boosted-trees